load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "full_upper_tracking_aar",
    calculators = ["//mediapipe/graphs/hand_tracking:full_upper_calculators"],
)